# Generated by Django 2.0.6 on 2018-06-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
