# Generated by Django 2.0.6 on 2018-06-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='hired',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
