# Generated by Django 2.0.6 on 2018-06-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_employees_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='group',
            field=models.CharField(choices=[('M', 'Manager'), ('A', 'Associate')], max_length=10, null=True),
        ),
    ]
