# Generated by Django 2.0.6 on 2018-06-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_employees_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='group',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Associate', 'Associate')], max_length=10, null=True),
        ),
    ]
